import { headers } from "next/headers"
import { notFound, redirect } from "next/navigation"
import type { Metadata } from "next"
import { createAdminClient, createClient } from "@/lib/supabase/server"
import { getBrandingSettings } from "@/lib/branding"
import { buildCheckinUrl, buildQrSvg, buildTalusMark } from "@/lib/qr-code"
import { PosterToolbar } from "./poster-toolbar"

export const dynamic = "force-dynamic"

// A lobby poster should never be indexed.
export const metadata: Metadata = {
    title: "Sign In Point",
    robots: { index: false, follow: false },
}

export default async function QrPosterPage({ params }: { params: Promise<{ locationId: string }> }) {
    const { locationId } = await params

    // Posters embed a live check-in token, so they are admin-only.
    const supabase = await createClient()
    const {
        data: { user },
    } = await supabase.auth.getUser()
    if (!user) redirect("/auth/login")

    const { data: profile } = await supabase.from("profiles").select("role").eq("id", user.id).single()
    if (profile?.role !== "admin") redirect("/admin")

    const admin = createAdminClient()
    const [{ data: location }, { data: code }, branding] = await Promise.all([
        admin.from("locations").select("id, name, address").eq("id", locationId).single(),
        admin
            .from("location_qr_codes")
            .select("token")
            .eq("location_id", locationId)
            .eq("is_active", true)
            .maybeSingle(),
        getBrandingSettings(),
    ])

    if (!location) notFound()

    // Resolve the public origin so the encoded link matches however admins reach the app.
    const headerList = await headers()
    const host = headerList.get("x-forwarded-host") ?? headerList.get("host") ?? ""
    const proto = headerList.get("x-forwarded-proto") ?? "https"
    const origin = host ? `${proto}://${host}` : ""

    if (!code) {
        return (
            <main className="mx-auto flex min-h-svh max-w-md flex-col items-center justify-center gap-4 p-8 text-center">
                <h1 className="text-xl font-semibold">No active QR code</h1>
                <p className="text-muted-foreground text-sm leading-relaxed">
                    {location.name} does not have an active check-in QR code yet. Generate one from Settings, then print the
                    poster.
                </p>
                <a className="text-sm underline" href="/admin/settings">
                    Go to Settings
                </a>
            </main>
        )
    }

    const checkinUrl = buildCheckinUrl(origin, code.token)
    // Large nominal size keeps the vector crisp; print scaling is handled in CSS.
    const qrSvg = buildQrSvg({ text: checkinUrl, size: 1100 })

    return (
        <>
            {/*
        Printable posters must be pure black on white paper regardless of the
        admin's light/dark theme, so this page opts out of theme tokens and
        fixes its own colours.
      */}
            <style>{`
        @page { size: A4 portrait; margin: 0; }
        @media print {
          html, body { background: #fff !important; }
          .poster-no-print { display: none !important; }
          .poster-sheet { box-shadow: none !important; margin: 0 !important; width: 210mm; height: 297mm; }
        }
      `}</style>

            <div className="min-h-svh bg-neutral-100 py-6 print:bg-white print:py-0">
                <PosterToolbar locationName={location.name} checkinUrl={checkinUrl} />

                <div className="poster-sheet mx-auto flex aspect-[210/297] w-[210mm] max-w-[95vw] flex-col items-center justify-between bg-white px-[14mm] py-[16mm] text-black shadow-lg">
                    <header className="flex w-full flex-col items-center gap-3">
                        <div className="flex items-center gap-4">
                            <ScanGlyph />
                            <h1 className="text-[42px] font-bold leading-none tracking-tight">Sign In Point</h1>
                        </div>
                        <p className="text-balance text-center text-[15px] leading-relaxed text-neutral-700">
                            Scan with your phone camera to sign in
                        </p>
                    </header>

                    <div className="relative my-[6mm]">
                        {/* Corner crop marks, matching a standard sign-in point poster. */}
                        <CropMarks />
                        <div
                            className="h-[105mm] w-[105mm] [&_svg]:h-full [&_svg]:w-full"
                            // Generated by our own builder from a fixed template.
                            dangerouslySetInnerHTML={{ __html: qrSvg }}
                        />
                    </div>

                    <p className="text-balance px-[6mm] text-center text-[17px] font-bold leading-snug">
                        Everyone must sign in when they arrive on site and sign out when they leave.
                    </p>

                    <footer className="flex w-full items-end justify-between gap-4 border-t border-neutral-200 pt-[6mm]">
                        <div className="flex items-center gap-3">
                            {branding.companyLogo ? (
                                // eslint-disable-next-line @next/next/no-img-element -- print fidelity: no optimisation/resampling
                                <img src={branding.companyLogo} alt={branding.companyName} className="h-[12mm] w-auto object-contain" />
                            ) : (
                                <>
                                    <span
                                        className="block h-[11mm] w-[11mm]"
                                        dangerouslySetInnerHTML={{ __html: wrapMark(buildTalusMark({ size: 32 })) }}
                                    />
                                    <span className="text-[15px] font-semibold">{branding.companyName}</span>
                                </>
                            )}
                        </div>
                        <div className="text-right">
                            <p className="text-[13px] uppercase tracking-wide text-neutral-500">Location</p>
                            <p className="text-[17px] font-semibold leading-tight">{location.name}</p>
                        </div>
                    </footer>
                </div>
            </div>
        </>
    )
}

/** Wrap raw mark markup in a scalable SVG shell. */
function wrapMark(markup: string) {
    return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32" width="100%" height="100%" role="img" aria-label="Talus">${markup}</svg>`
}

/** Small "scan me" phone-with-QR glyph shown beside the heading. */
function ScanGlyph() {
    return (
        <svg
            width="46"
            height="46"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="1.8"
            strokeLinecap="round"
            strokeLinejoin="round"
            aria-hidden="true"
        >
            <rect x="3" y="3" width="7" height="7" rx="1.5" />
            <rect x="14" y="3" width="7" height="7" rx="1.5" />
            <rect x="3" y="14" width="7" height="7" rx="1.5" />
            <path d="M14 14h3v3h-3zM20 14h1M14 20h3M20 20h1" />
        </svg>
    )
}

/**
 * Decorative registration brackets framing the QR code.
 *
 * Each mark is inset by the same offset on both axes so the four corners stay
 * symmetric around the code at any print scale.
 */
function CropMarks() {
    const base = "pointer-events-none absolute h-[9mm] w-[9mm] border-black"
    const inset = "-6mm"
    return (
        <>
            <span
                className={`${base} border-l-2 border-t-2`}
                style={{ top: inset, left: inset }}
                aria-hidden="true"
            />
            <span
                className={`${base} border-r-2 border-t-2`}
                style={{ top: inset, right: inset }}
                aria-hidden="true"
            />
            <span
                className={`${base} border-b-2 border-l-2`}
                style={{ bottom: inset, left: inset }}
                aria-hidden="true"
            />
            <span
                className={`${base} border-b-2 border-r-2`}
                style={{ bottom: inset, right: inset }}
                aria-hidden="true"
            />
        </>
    )
}
